---
output: github_document
---

# hecedsm

This **R** package contains data sets for the HEC Montreal PhD course MATH 80667A (Experimental Design and Statistical Methods).

Most of the databases are extracted from journal articles who shared their data on Open Science Foundation, on Research Box or otherwise.


You can install the package from Github using the following commands after installing `remotes`:

```{r}
#| eval: false
#| echo: true
# Uncomment this line if the package 'remotes' isn't installed
#install.packages("remotes") 
remotes::install_github("lbelzile/hecedsm")
```

```{r}
#| eval: true
#| echo: false
datasets <- read.csv("data-raw/datasets.csv", header = TRUE)[1:51,]
datasets$Title2 <- with(datasets, ifelse(DOI != "", paste0("[",Title,"]","(https://doi.org/", DOI, ")"), Title))
datasets$dataset <- with(datasets, paste0("[",Dataset,"]","(https://lbelzile.github.io/hecedsm/reference/", Dataset,".html)"))
datasets |> dplyr::select(dataset, Title2, Type) |>
  dplyr::arrange(dataset) |>
  knitr::kable(col.names = c("name", "source", "usage"))
```
